### ISSUE TITLE
Not enough arguments

### ISSUE THREAD

**Issue by jesa974** [p-/socket-connect-bpf#3]
Hello, I'm having a problem when I'm trying to `` go build `` your project. It says that there are not enough arguments in call to ``_Cfunc_bpf_module_create_c_from_string`` & ``_C2func_bpf_attach_uprobe``.

![image](https://user-images.githubusercontent.com/38524454/111331258-03510580-8671-11eb-9a89-056e3c4f475d.png)

**Comment by p-** [comment]
Hi @jesa974 
Please have a look at the new version of socket-connect-bpf. It's not based on gobpf anymore and should be easier to use/install.
